PREOPS-3286: Complete final version of document
lsst-sitcom/sitcomtn-014 pull request #11
Opened 2024-02-16 18:33 UTC by DukeofSuffolk

2024-02-21 14:58 UTC, leannep commented
I'd suggest removing 2.2.14 NOIRLab Risk Tool -- do we want to expose the risk register via the documentation portal?

2024-02-21 15:45 UTC, leannep commented
Do we want to expose Engineering Facility Database (EFD) information via the documentation portal? I wouldn't have thought so -- what is driving this?

2024-04-01 15:25 UTC, leannep requested changes

2024-04-01 15:25 UTC, leannep commented on StorageView.tex
> +In operations, the project will use openMAINT\textregistered\ as a customize Computerized Maintenance Management System (CMMS), with the assistance from the managing company, Tecnoteca srl\copyright
```suggestion
In operations, the project will use openMAINT\textregistered\ as a customizable Computerized Maintenance Management System (CMMS), with the assistance from the managing company, Tecnoteca srl\copyright . \citep{openmaint-cite}
```

2024-04-01 15:26 UTC, leannep commented
In Section 2.1.1 Departments, Data Production needs to be updated to Data Management 
"Data Production (DP) — The role of the Rubin Observatory Data Production department is" -> Data management

2024-04-02 18:43 UTC, leannep approved these changes

2024-04-03 14:39 UTC, cclaver approved these changes
All changes are excellent and should be merged with the Master

2024-04-06 01:26 UTC, merged